#强化插件配置文件
# 剑的每级伤害
sword: 1.5
# 弓箭的每级伤害
bow: 1.5
# 弩的每级伤害
crossbow: 1.3
# 护甲强化一级抵抗的伤害数值
defence: 0.5
# 当防御伤害高于攻击伤害（强化等级过高导致不掉血的刮痧伤害）
min_damage: 0.2
# 强化石是海绵 只支持单行lore，第一个是名字，第二个是lore.
stone_normal:
  - '§b强化石'
  - '§a用于强化武器和防具的好东西'
# 保护强化石是纸 只支持单行lore，第一个是名字，第二个是lore.
stone_safe:
  - '§c保护强化卷'
  - '§e用于保护超过8级之后的强化不导致武器破碎'
# 强化几率，总共十级
strength_chance:
  - 100
  - 90
  - 80
  - 70
  - 60
  - 50
  - 40
  - 30
  - 20
  - 10
#强化名称，必须要对的上物品名
itemName:
  - 'WOODEN_SWORD'
  - 'STONE_SWORD'
  - 'IRON_SWORD'
  - 'GOLDEN_SWORD'
  - 'DIAMOND_SWORD'
  - 'NETHERITE_SWORD'
  - 'WOODEN_AXE'
  - 'STONE_AXE'
  - 'IRON_AXE'
  - 'GOLDEN_AXE'
  - 'DIAMOND_AXE'
  - 'NETHERITE_AXE'
  - 'BOW'
  - 'CROSS_BOW'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'NETHERITE_HELMET'
  - 'NETHERITE_CHESTPLATE'
  - 'NETHERITE_LEGGINGS'
  - 'NETHERITE_BOOTS'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'GOLDEN_HELMET'
  - 'GOLDEN_CHESTPLATE'
  - 'GOLDEN_LEGGINGS'
  - 'GOLDEN_BOOTS'
